[package]
name = "VOCAN"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
eframe = "0.27.2"
egui = "0.27.2"
rfd = "0.14.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
walkdir = "2.5.0"
rayon = "1.10"
num_cpus = "1.16"

# new dependencies for DSP and temporary files
rustfft = "6.2"
biquad = "0.4"
nnnoiseless = "0.5"
tempfile = "3.10"
hound = "3.5"
